### ISSUE TITLE
GM Matrix

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#10]
I have some thoughts on creating a GM Matrix that allows the GM to quickly see the abilities, consequences, favours and possessions that the party has.

One implementation approach (taken from the gumshoe implementation from n3dst4) would be to create a Party Matrix = Actor, instead of Agent or Enemy.

This gives an empty matrix to then drag and drop characters into that populates the matrix with the character details, a mocked-up example is below, I would suggest the following nice-to-haves
 - only display items that are relevant to one or more characters e.g. if no one has the dance ability then don't show it
 - allow the description of occupation, damned affiliation, foci, consequence, favours to be shown when floated over or clicked
 - group possessions by the six tables - weapon, tool, printed matter, keepsakes, clothing, odds and ends
 - group or indicate abilities by occupation, affiliation, consequence
 - show chosen tradecraft(s), useful to see if the party is aligned on one or not
 -  expand/collapse each section - abilities/consequences/favours/posessions

![image](https://user-images.githubusercontent.com/244573/124379740-a4131180-dcb0-11eb-801d-4acf5b4d88c4.png)

**Comment by chrisesharp** [comment]
nice....a party sheet. Yes, I'll have a think about how I might do that. I've done a party sheet for OWB before, so got a rough idea, but this will be more advanced as it will be more dynamic based on the skills, items, etc.

**Comment by chrisesharp** [comment]
Just noticed on your example...it's my understanding of the rules that the party select a tradecraft for that adventure. So you don't actually have individual tradecrafts (even though it's on the char sheet, but has to be agreed as a group).

Which means that perhaps it would be good to set it on the party sheet, and that push down to the individual agents sheets.

**Comment by jwmuk** [comment]
Yes, tradecraft is set by the party, I thought it was useful to see where it is not set or set inconsistently, but your idea to set through the party matrix sounds even better!

**Comment by jwmuk** [comment]
Looks like the GM Matrix crashed when I tried to change the actors in the matrix and now it won't start after relaunching the world

**Comment by chrisesharp** [comment]
Whoa! That's interesting...can you look at the dev console and get a screenshot of any errors?
(That's Toggle Developer Tools in the FoundryVTT app menu and select Console)
I can't reproduce it so will need some error info.

**Comment by jwmuk** [comment]
when I press the button, I get no error/response, dev console says

![image](https://user-images.githubusercontent.com/244573/124602136-75d43400-de60-11eb-9961-93646c499459.png)

**Comment by jwmuk** [comment]
It could be that some users were changing actor names after I'd added them to the matrix

**Comment by chrisesharp** [comment]
Interesting. It seems that it was occuring when a player didn't have a character assigned (which maybe previously did?)...I think I've fixed it...I haven't generated a new version, so you'll need to uninstall and reinstall the system package but should be OK.

**Comment by jwmuk** [comment]
after an uninstall and reinstall, that seems to have fixed it, I'll do some more sophisticated tests later tonight

**Comment by chrisesharp** [comment]
Had a flash of inspiration and added new tabs for the party sheet, to cover abilities and possessions. Esoteric possessions are marked with a little magic icon.

Also, you can now no longer change an agent's tradecraft individually if they are a member of the party.

All in v1.0.9
