### ISSUE TITLE
Cannot add abilities to occupations

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#13]
I am creating a new occupation, I don't seem to be able to add abilities to this.  When I go to the Abilities tab of a new item (occupation), the cross appears but does nothing when I click on it.

![image](https://user-images.githubusercontent.com/244573/130347425-e6652712-39cb-4f5b-aeb4-fbfc69c8de81.png)

**Comment by chrisesharp** [comment]
You should be able to drag abilities onto the sheet and they then appear. The `+` should work to but I think I should remove it as it's redundant.
