### ISSUE TITLE
Select image when uploading

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#15]
Hi,

Would it be possible to select an item that you've just uploaded e.g. adding a character portrait,  I click on the portrait on the sheet, it takes me to the Image Browser and I Choose File to Upload.  When the file is returned, it is not Selected, so I have to then find the file, select it and upload it.

Thanks

**Comment by chrisesharp** [comment]
Hmm...this is weird. I have no idea what's causing this, as it's a default Foundry behaviour that I don't override. I'll see if I can figure out what's causing this.

**Comment by jwmuk** [comment]
I guess it may be that other systems just override this and select the file that's just been uploaded?
    On Sunday, 27 February 2022, 22:37:32 GMT, Chris Sharp ***@***.***> wrote:  
 
 


Hmm...this is weird. I have no idea what's causing this, as it's a default Foundry behaviour that I don't override. I'll see if I can figure out what's causing this.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chrisesharp** [comment]
Unfortunately not as simple as that....I have other systems where the default DOES work...and I can't see any difference in the code :-/

**Comment by chrisesharp** [comment]
Oh boy....that was a tricky one! It seems I had created a handlebar helper that was being used by jquery as a base function, so collided. I've learned something new today :-) 

Pushed new version 1.2.1 which should fix this.

**Comment by jwmuk** [comment]
Thanks Chris, I won't pretend to understand that 😁, but glad you found a fix, will try it out when I get home On 28 Feb 2022 10:56, Chris Sharp ***@***.***> wrote:
Oh boy....that was a tricky one! It seems I had created a handlebar helper that was being used by jquery as a base function, so collided. I've learned something new today :-)
Pushed new version 1.2.1 which should fix this.
