### ISSUE TITLE
Import of Sight Tables

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#18]
Hi Chris, 

Not sure if this is expected behaviour but the tables for Sight Outcomes and Sight Subject have to be imported from the compendium before the **O Fickle Fate** macro will work.  Otherwise, the Sight setting tickbox works fine.

Thanks for the updates!

**Comment by chrisesharp** [comment]
Hi Jim - did you delete the Macros and Outcomes folders, and re-initiatlize the system? That should have imported them correctly.
