### ISSUE TITLE
Players cannot move abilities from profession to character sheet

### ISSUE THREAD

**Issue by newbyr** [chrisesharp/foundryvtt-dee-sanction#19]
Hi Chris

I have set the permissions for my players as "Player" or "Trusted Player" for ALL permissions, but even then, they cannot drag & drop abilities from the Professions or Foci onto their character sheets.  This activity only works if you are a GM or GM Assistant.

Players can Drag & Drop from the compendium, but not from the side loaded professions etc.

I think there is something in the global permissions between GM and PLAYER that is doing this.

THanks
Richard N 

![Screenshot 2022-07-04 202148](https://user-images.githubusercontent.com/106149466/177203386-0b556aa4-0c7a-4e24-b097-7911c593963b.jpg)
 
![image](https://user-images.githubusercontent.com/106149466/177203751-ab466398-67b8-4f5c-8f8c-a7ca6dfa12a0.png)
![image](https://user-images.githubusercontent.com/106149466/177203827-a9969d86-aa2e-411f-84f0-29943d8156cb.png)
![image](https://user-images.githubusercontent.com/106149466/177203875-f6b99e1e-c7a2-42e9-9c4b-b1ead528911f.png)

**Comment by chrisesharp** [comment]
Hi Richard,

Hmmm...this is weird, and I imagine an artifact of Foundry v9. I confirm what you're seeing, but have no idea as yet, what is causing this. I'll dig in and find out.

**Comment by chrisesharp** [comment]
Hi @newbyr  - could you try updating to  v1.3.3 and confirming this fixes it? I've tried it and it appears to work.

**Comment by newbyr** [comment]
Hi Chris

This is super and works fine.  Agai , thanks for the rapid turn around.
My players love the module.

Richard

**Comment by newbyr** [comment]
Its great Chris.  Thank you so much for a quick response. My players love the adaption. Regards Richard   From: Chris SharpSent: 06 July 2022 17:58To: chrisesharp/foundryvtt-dee-sanctionCc: newbyr; MentionSubject: Re: [chrisesharp/foundryvtt-dee-sanction] Players cannot move abilities from profession to character sheet (Issue #19) Hi @newbyr - could you try updating to v1.3.3 and confirming this fixes it? I've tried it and it appears to work.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com
