### ISSUE TITLE
Association rather than Affilation

### ISSUE THREAD

**Issue by steveculshaw** [chrisesharp/foundryvtt-dee-sanction#20]
In the copy of the rules I have, the agent has an Occupation, a Focus and an **Association** ... there is no mention of any _Affiliation_ ???

And the Association shown on page 19, e.g. Star of Artemis, is added to the Affiliation tab

Are my rules out of date?

![image](https://user-images.githubusercontent.com/64320/177531365-a00f46be-a9b7-4c44-9c4c-51edfa9c28f2.png)

**Comment by chrisesharp** [comment]
Hi @steveculshaw purely historical - when I was originally designing the system I was intending to have more than just associations on that tab, so I needed a more generic, inclusive term - hence affiliations. However, in the end, I didn't need the new term, but didn't bother getting rid of it. 

As it happens, it's quite simple to fix, so I'll include it in the next version.

Thanks for using the system - hope you're enjoying it!

**Comment by steveculshaw** [comment]
Thanks for all the hard work you've done, and especially the ongoing support ... much appreciated
