### ISSUE TITLE
Foundry V10

### ISSUE THREAD

**Issue by newbyr** [chrisesharp/foundryvtt-dee-sanction#22]
Hi there.

I just updated my system to Foundry V10 b284.

I updated the Dee Sanction and now cannot access anything in my game world.  (!)  
I just get a blank "black" screen with the foundry logo top left - not even the icons on the right hand side for chat etc.

I have another rig with foundry on and have updated it to V10.  Other games have ported over ok.

I set up a new install of Dee, and it loaded, but when it asked to import the compendia, it said it had items to import to armor, consequences and items, and had now hung (dead).  

I have a backup of my old Dee world.

DO I try to revert to V9 or can we get Dee running on V10 ?

THanks

Richard

**Comment by newbyr** [comment]
Update.

I uninstalled V10 and reinstalled a fresh V9 B280.  Managed to copy into the rebooted Dee folders the backup.  GOt everything back up and running.

**Comment by chrisesharp** [comment]
Hi, sorry, only just saw this today. Yes, V10 is a trainwreck of an update...they've broken so much :-( It will take me a bit of time to update, but I'll let you know here when I have.

**Comment by chrisesharp** [comment]
@newbyr I have uploaded a new version 2.0.1 for FoundryVTT V10. 

I think I've caught everything, but please give it a good test and see if you can spot anything I might have missed.

Backup first, of course!

**Comment by newbyr** [comment]
Thanks Chris.

I have a week off from running Dee ,so I'll give it a blast next week.

Richard
