### ISSUE TITLE
Foundry v10-287 has broken it !

### ISSUE THREAD

**Issue by newbyr** [chrisesharp/foundryvtt-dee-sanction#24]
Hi Chris

I updated to Foundry 10 287 today from 286 and The Dee Sanction game screen was just blank.
I can get a log in to game screen, but when I log in, all I get is a blank canvas, no sidebar, and just the Foundry Anvil top left.

I have tried setting up a new world, and this hangs at importing the compendium items 
![image](https://user-images.githubusercontent.com/106149466/194703869-edbad915-d8d6-42a7-9b76-f3d699a876a5.png)

I don't know what they are doing at Foundry, but they certainly are causing problems for us.

Fortunately I cloned my complete setup to another machine and I won't ge updating to 287 for a while !  

Sorry to be a pain.

Richard N

**Comment by chrisesharp** [comment]
Hi Richard,

Hmm, I upgraded and couldn't replicate the problem. Could you go up to the Foundry menu and toggle Developer Tools, and get a screen cap of the console that will appear on the right-hand side? Maybe there are some error messages appearing that will help.

**Comment by newbyr** [comment]
Hi Chris I tried it again with a fresh install and all was ok.   Think my little server had a hissy fit and caused the problem. Thanks for trying it out. You can close the ticket. Regards Richard   From: Chris SharpSent: 10 October 2022 13:59To: chrisesharp/foundryvtt-dee-sanctionCc: newbyr; AuthorSubject: Re: [chrisesharp/foundryvtt-dee-sanction] Foundry v10-287 has broken it ! (Issue #24) Hi Richard,Hmm, I upgraded and couldn't replicate the problem. Could you go up to the Foundry menu and toggle Developer Tools, and get a screen cap of the console that will appear on the right-hand side? Maybe there are some error messages appearing that will help.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> Virus-free.www.avast.com
