### ISSUE TITLE
Empty Folders

### ISSUE THREAD

**Issue by Nyogtha68** [chrisesharp/foundryvtt-dee-sanction#26]
Hi, installed the latest version of the module on both Build 309 (via Forge) & 315 (on desktop) of Foundry and after hitting the import button all the folders for Dee Sanction in the compendium are empty.  I'm assuming this is because the content must be manually entered, but just wanted to double check there wasn't an error.

Cheers

**Comment by chrisesharp** [comment]
Hi @Nyogtha68 thanks for pointing this out! I don't know how this happened, but the zip file in v3.0.2 contained a mix of the legacy DB files from pre-V11 and empty DB folders from V11, and Foundry was failing to import the old legacy ldb files. This is now fixed in v3.0.3.

**Comment by Nyogtha68** [comment]
Excellent.  Great news, thank so much for this great mod.
