### ISSUE TITLE
Active falter options after selecting

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#4]
When you select attacking or defending after a challenge, the buttons are still active in the chat, should they become inactive when a choice is made?

![image](https://user-images.githubusercontent.com/244573/123323573-967dbf00-d52d-11eb-8204-e879dbd211a6.png)

**Comment by chrisesharp** [comment]
Good point! I've fixed this in v1.0.0 now so that the button you don't click is deleted and the button you clicked is then disabled.
