### ISSUE TITLE
Take a Chance missing?

### ISSUE THREAD

**Issue by jwmuk** [chrisesharp/foundryvtt-dee-sanction#6]
Does it make sense to add **Take a Chance** (pp13 rules) - a "coin" throw to determine a result - as a button on the character sheet?  I would add it to the Resources tab, along with the Intellectuall, Physicall and Supernaturall checks.

I can also see circumstances where it could be automated, e.g. when you reach 0 hits and are **Out of Action** (pp25 rules) but a lot of the time it's ad-hoc.

**Comment by chrisesharp** [comment]
Yes I wasn't quite sure what to do with take a chance, and defaulted to letting someone just roll a D2. It does feel like it should have a first-class presence, though, so I'll think about where best to put it. 

The trouble with having a take-a-chance linked to hits/falters automatically would mean it couldn't be used generically, and vice versa...maybe having it appear as a chat card button, generated by various circumstances (and therefore is possible to contextualise it's outcome) would be a good way. i.e. if you reach zero hits during a combat, it generates a chat-card button which would record a falter under the hits.

**Comment by jwmuk** [comment]
Maybe it is one of those items in the bucket of "play first and see how often it comes up", I'm only going on what I see in the rules and some of the monsters but there are lots of easy workarounds.

**Comment by chrisesharp** [comment]
I've been playing around and I've come up with a solution I think works. I've added a macro that allows anyone to "take a chance". If the person taking the chance is a player with a character on 0 hits, then it reminds them to mark off a falter. If they have two falters, it informs them they've died if they falter again .

**Comment by chrisesharp** [comment]
Implemented in v1.0.3
